### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by nolbyte** [mgilangjanuar/slimedoo#1]
Hallo
Pertamakali dijalankan di localhost dengan PHP Version 5.4.45 saya mendapatkan error 403 forbidden.
Terimakasih

**Comment by mgilangjanuar** [comment]
Dear nolbyte,

403 Forbidden pada awal konfigurasi hanya muncul untuk beberapa kasus seperti saat user masuk ke /admin atau ke controller yang memerlukan authentication khusus seperti yang ada di app/controllers/admin/*. Pastikan untuk sudah import table Users dan register sebelumnya melalui /site/register.

**Comment by nolbyte** [comment]
Terimakasih mas Gilang,

Apa yang saya coba lakukan adalah menonaktifkan htaccess, hasilnya white blank space. Kemudian saya tambahkan script pada /app/config/autoload.php
error_reporting(E_ALL);
ini_set('display_errors', 1);

hasilnya adlah error berikut:
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\UniServerZ\www\slimedoo\app\config\autoload.php on line 7 Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.;C:/UniServerZ/home/us_pear/PEAR') in C:\UniServerZ\www\slimedoo\app\config\autoload.php on line 7

Kemudian ada error seperti ini juga:
Warning: require(app/config/config.php): failed to open stream: No such file or directory in C:\UniServerZ\www\slimedoo\app\system\App.php on line 69 Fatal error: require(): Failed opening required 'app/config/config.php' (include_path='.;C:/UniServerZ/home/us_pear/PEAR') in C:\UniServerZ\www\slimedoo\app\system\App.php on line 69

**Comment by mgilangjanuar** [comment]
Oh iya saya paham masalahnya, pastikan untuk sudah melakukan update melalui composer di directory C:\UniServerZ\www\slimedoo\ dengan cara ketik di console:

```
cd C:\UniServerZ\www\slimedoo
composer update
```

**Comment by nolbyte** [comment]
Terimakasih.
Masalah error di atas sudah tertangani dengan update composer.
Sebagai catatan, saya mencoba aplikasi ini di localhost dengan apache dan server produksi dengan nginx. Untuk nginx semua running tanpa error apa-apa. Untuk localhost apache di versi PHP yang saya sebutkan diatas saya menemukan 2 error:
1. Jika htaccess diaktifkan, halaman akan mengahasilkan 403 forbidden. Saya tidak begitu faham konsep rewrite. Saya mencoba di uniform server, entah di xampp.
2. Jika htaccess dimatikan, halaman menghasilkan error:
Fatal error: Class '\C:\UniServerZ\www\slimedoo\app\controllers\SiteController' not found in C:\UniServerZ\www\slimedoo\app\config\autoload.php on line 34
Padahal file tersebut ada dan spt saya sebutkan diatas, aplikasi running smooth di nginx.

Demikian, terimakasih

**Comment by mgilangjanuar** [comment]
Terima kasih atas laporan bug yang terjadi, akan segera saya coba kembangkan lebih lanjut.
